### ISSUE TITLE
As a user, I need a login page to login my account

### ISSUE THREAD

**Issue by xdjeremy** [TamJer/maiserve#2]
## Todo
- [x] Initialize story book
- [x] Create button component
- [x] Create Input component
- [x] Login Form
- [x] Page background
- [x] Implement New Font
